### ISSUE TITLE
INFOGRAFÍA DE LIBRERÍA

### ISSUE THREAD

**Issue by Rigoberto2001** [SistemasTecTlaxiaco/infografia-de-las-librerias-Rigoberto2001#2]
![INFOGRAFIATOPICOS_RIGOBERTORAMIREZNICOLAS](https://user-images.githubusercontent.com/79929662/114480180-a55c0300-9bc7-11eb-9d9d-a0c0614cb85d.png)

**Comment by garaudy12** [comment]
Calificación: 17 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
